all:04

04: main.o Car.o MCycle.o Truck.o Vehicle.o
	g++ -o 04 main.o Car.o MCycle.o Truck.o Vehicle.o
    
06_04.o: main.cpp
	g++ -c main.cpp
    
Car.o: Car.cpp
	g++ -c Car.cpp
    
MCycle.o: MCycle.cpp
	g++ -c MCycle.cpp
	
Truck.o: Truck.cpp
    g++ -c Truck.cpp
    
Vehicle.o: Vehicle.cpp
	g++ -c Vehicle.cpp
